/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CaracteristicasRouteImport } from './routes/caracteristicas'
import { Route as DemostracionRouteImport } from './routes/demostracion'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppAnaliticaRouteImport } from './routes/app.analitica'
import { Route as AppClinicaRouteImport } from './routes/app.clinica'
import { Route as AppComunicacionRouteImport } from './routes/app.comunicacion'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppEquipoRouteImport } from './routes/app.equipo'
import { Route as AppEstudiosDiagnosticoRouteImport } from './routes/app.estudios-diagnostico'
import { Route as AppFinanzasRouteImport } from './routes/app.finanzas'
import { Route as AppIaEstherRouteImport } from './routes/app.ia-esther'
import { Route as AppIntegracionesRouteImport } from './routes/app.integraciones'
import { Route as AppInventarioRouteImport } from './routes/app.inventario'
import { Route as AppLaboratorioRouteImport } from './routes/app.laboratorio'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppMultiempresaRouteImport } from './routes/app.multiempresa'
import { Route as AppNotificacionesRouteImport } from './routes/app.notificaciones'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppPortalPacienteRouteImport } from './routes/app.portal-paciente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CaracteristicasRoute = CaracteristicasRouteImport.update({
  id: '/caracteristicas',
  path: '/caracteristicas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemostracionRoute = DemostracionRouteImport.update({
  id: '/demostracion',
  path: '/demostracion',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAnaliticaRoute = AppAnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicaRoute = AppClinicaRouteImport.update({
  id: '/clinica',
  path: '/clinica',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacionRoute = AppComunicacionRouteImport.update({
  id: '/comunicacion',
  path: '/comunicacion',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipoRoute = AppEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudiosDiagnosticoRoute = AppEstudiosDiagnosticoRouteImport.update({
  id: '/estudios-diagnostico',
  path: '/estudios-diagnostico',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppIaEstherRoute = AppIaEstherRouteImport.update({
  id: '/ia-esther',
  path: '/ia-esther',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracionesRoute = AppIntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppLaboratorioRoute = AppLaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppMultiempresaRoute = AppMultiempresaRouteImport.update({
  id: '/multiempresa',
  path: '/multiempresa',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalPacienteRoute = AppPortalPacienteRouteImport.update({
  id: '/portal-paciente',
  path: '/portal-paciente',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/caracteristicas': typeof CaracteristicasRoute
  '/demostracion': typeof DemostracionRoute
  '/planes': typeof PlanesRoute
  '/registro': typeof RegistroRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analitica': typeof AppAnaliticaRoute
  '/app/clinica': typeof AppClinicaRoute
  '/app/comunicacion': typeof AppComunicacionRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipo': typeof AppEquipoRoute
  '/app/estudios-diagnostico': typeof AppEstudiosDiagnosticoRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/ia-esther': typeof AppIaEstherRoute
  '/app/integraciones': typeof AppIntegracionesRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/laboratorio': typeof AppLaboratorioRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/multiempresa': typeof AppMultiempresaRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/portal-paciente': typeof AppPortalPacienteRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caracteristicas': typeof CaracteristicasRoute
  '/demostracion': typeof DemostracionRoute
  '/planes': typeof PlanesRoute
  '/registro': typeof RegistroRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analitica': typeof AppAnaliticaRoute
  '/app/clinica': typeof AppClinicaRoute
  '/app/comunicacion': typeof AppComunicacionRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipo': typeof AppEquipoRoute
  '/app/estudios-diagnostico': typeof AppEstudiosDiagnosticoRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/ia-esther': typeof AppIaEstherRoute
  '/app/integraciones': typeof AppIntegracionesRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/laboratorio': typeof AppLaboratorioRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/multiempresa': typeof AppMultiempresaRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/portal-paciente': typeof AppPortalPacienteRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/caracteristicas': typeof CaracteristicasRoute
  '/demostracion': typeof DemostracionRoute
  '/planes': typeof PlanesRoute
  '/registro': typeof RegistroRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analitica': typeof AppAnaliticaRoute
  '/app/clinica': typeof AppClinicaRoute
  '/app/comunicacion': typeof AppComunicacionRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipo': typeof AppEquipoRoute
  '/app/estudios-diagnostico': typeof AppEstudiosDiagnosticoRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/ia-esther': typeof AppIaEstherRoute
  '/app/integraciones': typeof AppIntegracionesRoute
  '/app/inventario': typeof AppInventarioRoute
  '/app/laboratorio': typeof AppLaboratorioRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/multiempresa': typeof AppMultiempresaRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/portal-paciente': typeof AppPortalPacienteRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/caracteristicas'
    | '/demostracion'
    | '/planes'
    | '/registro'
    | '/app/agenda'
    | '/app/analitica'
    | '/app/clinica'
    | '/app/comunicacion'
    | '/app/configuracion'
    | '/app/documentos'
    | '/app/equipo'
    | '/app/estudios-diagnostico'
    | '/app/finanzas'
    | '/app/ia-esther'
    | '/app/integraciones'
    | '/app/inventario'
    | '/app/laboratorio'
    | '/app/marketing'
    | '/app/multiempresa'
    | '/app/notificaciones'
    | '/app/pacientes'
    | '/app/portal-paciente'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caracteristicas'
    | '/demostracion'
    | '/planes'
    | '/registro'
    | '/app/agenda'
    | '/app/analitica'
    | '/app/clinica'
    | '/app/comunicacion'
    | '/app/configuracion'
    | '/app/documentos'
    | '/app/equipo'
    | '/app/estudios-diagnostico'
    | '/app/finanzas'
    | '/app/ia-esther'
    | '/app/integraciones'
    | '/app/inventario'
    | '/app/laboratorio'
    | '/app/marketing'
    | '/app/multiempresa'
    | '/app/notificaciones'
    | '/app/pacientes'
    | '/app/portal-paciente'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/caracteristicas'
    | '/demostracion'
    | '/planes'
    | '/registro'
    | '/app/agenda'
    | '/app/analitica'
    | '/app/clinica'
    | '/app/comunicacion'
    | '/app/configuracion'
    | '/app/documentos'
    | '/app/equipo'
    | '/app/estudios-diagnostico'
    | '/app/finanzas'
    | '/app/ia-esther'
    | '/app/integraciones'
    | '/app/inventario'
    | '/app/laboratorio'
    | '/app/marketing'
    | '/app/multiempresa'
    | '/app/notificaciones'
    | '/app/pacientes'
    | '/app/portal-paciente'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CaracteristicasRoute: typeof CaracteristicasRoute
  DemostracionRoute: typeof DemostracionRoute
  PlanesRoute: typeof PlanesRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caracteristicas': {
      id: '/caracteristicas'
      path: '/caracteristicas'
      fullPath: '/caracteristicas'
      preLoaderRoute: typeof CaracteristicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demostracion': {
      id: '/demostracion'
      path: '/demostracion'
      fullPath: '/demostracion'
      preLoaderRoute: typeof DemostracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analitica': {
      id: '/app/analitica'
      path: '/analitica'
      fullPath: '/app/analitica'
      preLoaderRoute: typeof AppAnaliticaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinica': {
      id: '/app/clinica'
      path: '/clinica'
      fullPath: '/app/clinica'
      preLoaderRoute: typeof AppClinicaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comunicacion': {
      id: '/app/comunicacion'
      path: '/comunicacion'
      fullPath: '/app/comunicacion'
      preLoaderRoute: typeof AppComunicacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipo': {
      id: '/app/equipo'
      path: '/equipo'
      fullPath: '/app/equipo'
      preLoaderRoute: typeof AppEquipoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estudios-diagnostico': {
      id: '/app/estudios-diagnostico'
      path: '/estudios-diagnostico'
      fullPath: '/app/estudios-diagnostico'
      preLoaderRoute: typeof AppEstudiosDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finanzas': {
      id: '/app/finanzas'
      path: '/finanzas'
      fullPath: '/app/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia-esther': {
      id: '/app/ia-esther'
      path: '/ia-esther'
      fullPath: '/app/ia-esther'
      preLoaderRoute: typeof AppIaEstherRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integraciones': {
      id: '/app/integraciones'
      path: '/integraciones'
      fullPath: '/app/integraciones'
      preLoaderRoute: typeof AppIntegracionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario': {
      id: '/app/inventario'
      path: '/inventario'
      fullPath: '/app/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/laboratorio': {
      id: '/app/laboratorio'
      path: '/laboratorio'
      fullPath: '/app/laboratorio'
      preLoaderRoute: typeof AppLaboratorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/multiempresa': {
      id: '/app/multiempresa'
      path: '/multiempresa'
      fullPath: '/app/multiempresa'
      preLoaderRoute: typeof AppMultiempresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificaciones': {
      id: '/app/notificaciones'
      path: '/notificaciones'
      fullPath: '/app/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal-paciente': {
      id: '/app/portal-paciente'
      path: '/portal-paciente'
      fullPath: '/app/portal-paciente'
      preLoaderRoute: typeof AppPortalPacienteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAnaliticaRoute: typeof AppAnaliticaRoute
  AppClinicaRoute: typeof AppClinicaRoute
  AppComunicacionRoute: typeof AppComunicacionRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEquipoRoute: typeof AppEquipoRoute
  AppEstudiosDiagnosticoRoute: typeof AppEstudiosDiagnosticoRoute
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppIaEstherRoute: typeof AppIaEstherRoute
  AppIntegracionesRoute: typeof AppIntegracionesRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppLaboratorioRoute: typeof AppLaboratorioRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMultiempresaRoute: typeof AppMultiempresaRoute
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppPortalPacienteRoute: typeof AppPortalPacienteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAnaliticaRoute: AppAnaliticaRoute,
  AppClinicaRoute: AppClinicaRoute,
  AppComunicacionRoute: AppComunicacionRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEquipoRoute: AppEquipoRoute,
  AppEstudiosDiagnosticoRoute: AppEstudiosDiagnosticoRoute,
  AppFinanzasRoute: AppFinanzasRoute,
  AppIaEstherRoute: AppIaEstherRoute,
  AppIntegracionesRoute: AppIntegracionesRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppLaboratorioRoute: AppLaboratorioRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMultiempresaRoute: AppMultiempresaRoute,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppPortalPacienteRoute: AppPortalPacienteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CaracteristicasRoute: CaracteristicasRoute,
  DemostracionRoute: DemostracionRoute,
  PlanesRoute: PlanesRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
